### ISSUE TITLE
Run the website on your computer 

### ISSUE THREAD

**Issue by jacob-umich** [jacob-umich/stats-dash#1]
Hello everyone, 

the professor gave us an example website for us to modify. Our first task is to make sure everyone can get set up and run the website so we all can make meaningful modifications. This will include

1. cloning the git repository
2. setting up your python and computer environment as specified in the repository's main page
3. running the website
4. making a change to the website
5. uploading your changes here

if you don't use a windows computer and need help setting up everything, I can probably help. Just let me know. Reply to this issue when you have successfully ran the website on your own computer. Once you make a change to the website, use git and github to upload your changes.

**Comment by jacob-umich** [comment]
I successfully ran the website on my computer and made a small change

**Comment by tsivitse** [comment]
Hi everyone, I ran the website and made a small change

**Comment by jacob-umich** [comment]
@tsivitse  I don't see your change in the repository. Can you upload your change?

**Comment by jacob-umich** [comment]
@Aerlenbeck you will have to push your changes to this repository and pull my changes if you cloned the repository before I made my small change. In terms of the commands not working, what type of computer do you have?

**Comment by Aerlenbeck** [comment]
@jacob-umich  I have mac and windows and the commands do not work on either system.

I am following her instructions from class, so I believe my issue is I am pulling from her files on gitlab as opposed to connecting to this module or whatever it is called on our group specific github.

**Comment by Aerlenbeck** [comment]
Hi everyone, I was able to clone the repository and make a small change (finally seeing everyone's changes now) but I am having difficulty pushing my change back to the original github file I am getting this error:


(myenv) alyssaer@cloudshell:~/stats-dash$ git push
Username for 'https://github.com': Aerlenbeck
Password for 'https://Aerlenbeck@github.com': 
remote: Permission to jacob-umich/stats-dash.git denied to Aerlenbeck.
fatal: unable to access 'https://github.com/jacob-umich/stats-dash.git/': The requested URL returned error: 403
(myenv) alyssaer@cloudshell:~/stats-dash$  

My question- is this an access issue, or is it something on my end? I using the HTTPS connection instead of SSH, not sure if that makes a difference. For password I generated a personal token and pasted that.

**Comment by Aerlenbeck** [comment]
@jacob-umich I tried to push the updates with SSH key but I also was unable to push updates that way. 

I joined OH with the professor this morning and she recommended I use HTTPS and personal access token but I encountered the same access issue. She said this is because I do not have access to push to out Github here.

Since we are kind of getting close to submission I am a little anxious to start working on the project. She said I can work on things outside the github and then upload and code or changes manually via files. I think this may work if you all are okay with it.

**Comment by jacob-umich** [comment]
@Aerlenbeck I was looking at the https method last night. I think it might not be working because it's my repository and not yours. There are special permissions you have to set when you create the person access token too. It might have something to do with that too. 

In regards to ssh not working. I noticed last night it looked like you were working on a virtual machine. If you try to push from a virtual machine but created your private key on your laptop, that won't work. But I'm not sure what the issue would be otherwise.

I checked last night, and it says you're a collaborator on this project so that shouldn't be an issue. 

But we can work manually uploading your changes for now

**Comment by jacob-umich** [comment]
Another thing you might try is pushing to another branch

`git push origin main:test`

**Comment by jacob-umich** [comment]
Ok sounds good. Look at my most recent changes on the eda branch. I picked out some data sets and started cleaning the data

**Comment by Aerlenbeck** [comment]
I was able to find that tab. I don't see any datasets under the data folder though, where did you upload the datasets you added?

@jacob-umich

**Comment by jacob-umich** [comment]
> @jacob-umich I did try to push from a virtual environment and I did generate the key on my laptop, so that is likely the error. I am unsure how else I should go about generating/using the key. I have never used SSH before and was 100% relying on chatgpt/google to guide me.

It would probably be more clear to explain it in person, but i can try here.

you would want to clone the repository onto your laptop. Open a terminal and navigate to wherever you want the files to be downloaded to. Then, use git clone and use the ssh address instead of the http address. so, `git clone git@github.com:jacob-umich/stats-dash.git`. Then, since the repository is on the same computer as your SSH keys, the OpenSSH software that was installed with git will automatically find them and allow you access. One thing to double check too is that you put your public key on your github and not your private key.

> I don't see any datasets under the data folder though, where did you upload the datasets you added? 

github gets upset when you upload large datasets to it, so i decided not to include them. I was working on compiling them all into one sqlite database but I haven't made it that far. I will upload them to a google drive folder and share them. You can still download the data from its original source though. It just came from the links that the professor provided in the project description.

**Comment by jacob-umich** [comment]
@amandarcicali how is your progress?

**Comment by amandarcicali** [comment]
@jacob-umich I didn't have time to get this working yesterday. I've been trying to get it set up and running today, but I'm struggling to get git on my mac

**Comment by jacob-umich** [comment]
@Aerlenbeck @amandarcicali  I can probably help you both set it up tomorrow after class if you have time and are available

**Comment by Aerlenbeck** [comment]
@jacob-umich Sounds good

**Comment by Aerlenbeck** [comment]
@jacob-umich Actually, I have to teach at 1 tomorrow. Could we meet before class instead?

**Comment by Aerlenbeck** [comment]
@jacob-umich It's okay, if Amanda can figure it out she can show me how to do it too.

**Comment by amandarcicali** [comment]
@jacob-umich @Aerlenbeck Since class was moved to zoom today, would you guys want to meet up during class time and get everything working?

**Comment by jacob-umich** [comment]
@amandarcicali  that works for me

**Comment by Aerlenbeck** [comment]
@amandarcicali @jacob-umich We have conference room 4742 reserved in the Chemistry building at 11:30AM

**Comment by tsivitse** [comment]
@jacob-umich when you showed me how to do the setup in class, I was pushing the repo using my wife's account. I tried to redo the setup under my name, but I'm now getting this error when I try to follow your steps you listed on the homepage: 
PS C:\Users\CTsiv\OneDrive - Umich\Desktop\507project> py -V:3.9 -m venv .venv
py : The term 'py' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At line:1 char:1
+ py -V:3.9 -m venv .venv
+ ~~
    + CategoryInfo          : ObjectNotFound: (py:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

I verified that I have python installed...not sure why I can't get the virtual environment working..do you have any idea?

**Comment by Aerlenbeck** [comment]
@tsivitse Is your python version 3.9? I had downloaded python 3.12 and I had the same exact error.

**Comment by tsivitse** [comment]
Yeah I verified it’s 3.9

**Comment by jacob-umich** [comment]
@tsivitse so using `py` instead of `python` only works if you installed python from the python website. If you installed it any other way, it might not work.

Type `python --version` and see what pops up. If it's 3.9, you can just type `python -m venv .venv`. If it's something else (e.g. 3.10) you have to find the specific path for python 3.9 executable and use that `C:/path/to/python -m venv .venv`

**Comment by jacob-umich** [comment]
@tsivitse the py command is called the "python launcher for windows" https://docs.python.org/3/using/windows.html#launche

**Comment by tsivitse** [comment]
My version is Python 3.9.13. I believe the python -m venv .venv command worked. I also did the git clone using the HTTPS link. When I go to install the requirements, I get this error: 

(.venv) PS C:\Users\CTsiv\OneDrive - Umich\Desktop\stats507> pip install -r .\requirements.txt
ERROR: Could not open requirements file: [Errno 2] No such file or directory: '.\\requirements.txt'
WARNING: You are using pip version 22.0.4; however, version 24.0 is available.
You should consider upgrading via the 'C:\Users\CTsiv\OneDrive - Umich\Desktop\stats507\.venv\Scripts\python.exe -m pip install --upgrade pip' command.

**Comment by jacob-umich** [comment]
@tsivitse 

> I also did the git clone using the HTTPS link.

Youll want to clone it using SSH. That way, you will be able to upload your changes using your ssh key. 

> When I go to install the requirements, I get this error:

if you are in one directory (stats507) and clone a repository, git puts the entire contents of the repository in a new folder with the same name as the repository. after cloning, you'll want to use `cd stats-dash`. You want to make the virtual environment in that folder and `pip install -r .\requirements.txt` will work

**Comment by tsivitse** [comment]
I got it to work, thanks Jacob
