### ISSUE TITLE
train linear regression model

### ISSUE THREAD

**Issue by jacob-umich** [jacob-umich/stats-dash#10]
we need to try 3 types of models for our machine learning model. linear regression works well for small data. Using the training data from get_data, use the first 3 columns to predict the last column. Info on how to train a linear regression model  is here

You need to create a function that takes in the data and model args, then returns the trained model

```
def train_regression(training, alpha):
# train the model
return model
```

https://scikit-learn.org/stable/modules/linear_model.html#lasso

**Comment by Aerlenbeck** [comment]
where is get_data? I don't see it under data_handler.py

**Comment by jacob-umich** [comment]
@Aerlenbeck switch to the machine learning branch. All of the stuff you'll need is in the train_model.py file

**Comment by Aerlenbeck** [comment]
1. Where do you want me to put my model? In the .py file you already made for get_data? 
2. I think the model is working. I made fake data with columns sleep, smoke, obese, and rate in a nparray called "test" (so everything should be the same) and it is working with the fake data, but is there a way for me to test if this model is working?

**Comment by jacob-umich** [comment]
1. yes in the same file please
2. once you put the function in the train_model file, test it with the data at the bottom of the file after `if __name__=="__main__"`

```
if __name__=="__main__":
train,test = get_data()
model = train_regression()
results = model.predict(test_x)
```
something like that

**Comment by Aerlenbeck** [comment]
> 2. once you put the function in the train_model file, test it with the data at the bottom of the file after `if __name__=="__main__"`
> 
> 
> 
> ```
> 
> if __name__=="__main__":
> 
> train,test = get_data()
> 
> model = train_regression()
> 
> results = model.predict(test_x)
> 
> ```
> 
> something like that

But where can I run this? If I run it in colab it won't work because of the .dh stuff, I already tried with earlier data.

**Comment by jacob-umich** [comment]
I just run it on my computer the same way you ran main.py when we were running the website on our own computers

`python train_model.py`

**Comment by Aerlenbeck** [comment]
But when I normally run the website I'm not able to see or test the code either. I can only see the link for the website and the actual webpage. I have only ever been able to run this code in colab.

**Comment by jacob-umich** [comment]
yea you're right. to do any kind of debugging you would have to some other steps im not familiar with. One thing you can do is just print the end result. if it gets all the way to the end without throwing an error and the result looks right, then you can be pretty confident it is working as intended

**Comment by Aerlenbeck** [comment]
But how can I print the end result if I can't run the code? Sorry I know these are stupid questions.

**Comment by jacob-umich** [comment]
everything in the train_model.py file will run if you type the command `python train_model.py`

```
if __name__=="__main__":
train,test = get_data()
model = train_regression()
results = model.predict(test_x)
print(results)
```

you should see something print

**Comment by Aerlenbeck** [comment]
Okay I have to stop for today but will try this tomorrow. Do you know how to switch different branches in terminal? Like I'm in EDA I think and can only see those files.

**Comment by jacob-umich** [comment]
yes.  type:

`git switch machine-learning`

then, make sure you have the latest version:

'git pull'

If that doesn't work, type `git fetch` and repeat all the other steps

you can check what branch you're on by using 'git branch'

I am going to hop off too

**Comment by Aerlenbeck** [comment]
Okay I got it to run and it looks good. It is outputting rate in the high 70s so seems to be doing an ok job predicting rate.
