### ISSUE TITLE
Create Decision Tree model

### ISSUE THREAD

**Issue by jacob-umich** [jacob-umich/stats-dash#9]
we need to try 3 types of models for our machine learning model. Decision trees work well for small data. Using the training data from get_data, use the first 3 columns to predict the last column. Info on how to train a decision tree is here

https://scikit-learn.org/stable/modules/tree.html#regression

You need to create a function in the `train_model.py` file that takes in the data and model args, then returns the trained model

```
def train_dt(training, leafs,nodes,etc):
# train the model
return model
```

**Comment by amandarcicali** [comment]
I added a function but I'm still checking to make sure the model works correctly

**Comment by jacob-umich** [comment]
It looks good!
